export enum EntityTypeEnum {
    Recipe = 1,
    Saved = 2,
    Follower = 3,
    Followed = 4,
    Favorite = 5,
    Comment = 6,
    Shopping = 7,
    Flow = 8,
    Basket = 9,
    Activity = 10,
    Product = 11,
    MyProduct = 12,
    MyActivity = 13,
    Notification = 14,
    MyOrders = 15,
    MySales = 16,
    Ticket = 17,
    MyRecipe = 18,
    Question = 19,
    Address = 20,
}